# Copyright 2023 Michael Ripley
# This file is part of barotrauma-compress.
# barotrauma-compress is licensed under the AGPL-3.0 license (see LICENSE file for details).

name: Publish
on:
  workflow_dispatch:
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
